version: '{build}'
clone_depth: 3 
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64/
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      JAVA_HOME: C:\Program Files\Java\jdk11
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      JAVA_HOME: C:\Program Files\Java\jdk17
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      JAVA_HOME: C:\Program Files\Java\jdk21  
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64/
      DEPLOY: 1
matrix:
  fast_finish: true
install:
  - bash -c "mkdir -p $HOME/.m2"
build_script:
  - mvn install --settings .ci-settings.xml -DskipTests=true -U -B
test_script:
  - mvn test -Dassembly.skipAssembly=true -B
deploy_script:
  - bash -c "if [ ${DEPLOY} ] && [ ${APPVEYOR_REPO_BRANCH} = 'main' ]; then mvn deploy --settings .ci-settings.xml -DskipTests=true -B; fi"   
cache:
  - $HOME/.m2/