version: '{build}'
image: Visual Studio 2019
clone_depth: 3 
environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    - JAVA_HOME: C:\Program Files\Java\jdk9
    - JAVA_HOME: C:\Program Files\Java\jdk11
    - JAVA_HOME: C:\Program Files\Java\jdk17
    - JAVA_HOME: C:\Program Files\Java\jdk21
install:
  - cmd: SET PATH=%JAVA_HOME%\bin;%PATH%
build_script:
  - mvn install -DskipTests=true
test_script:
  - mvn test -Dassembly.skipAssembly=true -B
cache:
  - C:\Users\appveyor\.m2
