language: java

git:
  depth: 3

matrix:
  include:
   - jdk: openjdk6
     env: OPTIONS='-pl !elk-owlapi,!elk-owlapi-standalone,!elk-protege,!elk-distribution'
   - jdk: oraclejdk7
     env: DEPLOY=true
   - jdk: openjdk7
   - jdk: oraclejdk8

install: mvn install -DskipTests=true $OPTIONS

script: mvn test -Dassembly.skipAssembly=true -B $OPTIONS

after_success:
  - test "$DEPLOY" = true -a "$TRAVIS_PULL_REQUEST" = false -a "$TRAVIS_BRANCH" = master
    && mvn source:jar deploy --settings .travis-settings.xml -DskipTests=true -B

env:
  global:
  - secure: cV/cG1G/M73A13bfPalNhhChC26kNZyCWkU6QuPReuncRSpUckNYvAxP2hrwrnQ4H2MXDjom4tqwheCGCTdaWg2viti7bvgZdOHURm3Qsno5DtFvKO041FgXEKNNmf4si8Ds2TWmVdJ1kt5hEHjO+hahT7YYyw9Vf52s6K7Qgr0xFvElrFoKCeHEItsiDS6FDpIIznceUipdPwruStnn2cFBju9YaN4fc8OuuTYXcaQNZ9AgqqSEPg06dck5YveKSsa5RDzOT9S/+aF2koWFWMGxl0o3lnq6QFRI2qN0frTGp5ovnVXSaqioAJcGLJxv7HMs067r0jn/W6JDauE4dkBkWYm1Uh22rWAUbIL/Nb9skU5LwSqUIdV4jagC39iVAIun0vcef5KhGQ2jwG3OngTIlL0TqPEWWAJyBroU+Ydc+mj/CAHBRN3OaH8qG+wXSdigEt9v3VaRGqhogir/zNEOH05S5kOucZQjNA3Gmik7UxcHXGQyp9K6u2X5nZpxW382I+6UXUYaozSZY9Ch/01ljVUI3WWSxkD1Jq31TYLSs1amLqTUmkKjyXO8pd45BxQCw+k5gjTroCXJW9L1XLkeheYvf4qKDkNbMgM59L78L8zt0xGzCzR3tg5MoP8vDt91nn3UIDfQL05HyhZRU3G6CYRQysN/DBGE3l8U1oI=
  - secure: YikcGqQnSv7R85ZftdXRVJcTEJ4V9Zedfh29AeQoXwG1xmv0HvC3lS+w4ZNqf3jl6RYgUHi4PjOFQB6zXtANjxBEIb32hko14OKIOXsbYB/w1iRdwi2X3eVHeBYUxWjX6GkImECi5JuAPb+NIYcOwUxGl/7vMGK6FwugJsaEtvZdMA/wVSHcK38yNnVbAFKwZwPttUu77AToDGIjnyT+XMy3BR3xYTF/TAUkVJn998cCMqfuZ8p1sFcOAsOranNCFmCjDGlRHcHt/6jcNq73ZHxWWlS3xmTuf1TO8QpEwVFWDT5tYQvQPXUjhsq8GC+qBiOpJGEUx1moyzN5IFf8vTJbLAHHGH3rX2eDlt53ALeofwpmHVLKRNovIxPDAGpcGbK2dAGQQdOrXiejyrAEOn9t2tZAkoJJ+aCvDLykEZfwHi9Ld1l432w74qC274tAYXO6bidYlWdt/GceYWwg2qhSgeGGblz+WOqrthYOcLKbP8YdkW97nYCrJEHSViPosHoYGzseUrwXNFFG90nio4wYKqjVvJ0ihQYR1qM997DJ50wVBq5YOI41j55CehGqTZWXiseNUNc8Qa6n4mmZeOY4/Oh3lbcO7VdTmQVhGXyxkR8WLIgeS3Q738IJW5HgiNIyvp8PItubZVsEiebLnuNVIkdG58LzsGR+la9+W7k=
